/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Appointment } from './Appointment.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AppointmentService } from './Appointment.service';
import { AppointmentController } from './Appointment.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Appointment])],
  providers: [AppointmentService],
  exports: [AppointmentService],
  controllers: [AppointmentController],
})
export class AppointmentModule {}
