/**
 * This file generated by Apso.
 */
import { Controller } from '@nestjs/common';
import {
  Crud,
  CrudController,
  Override,
  ParsedRequest,
  CrudRequest,
  ParsedBody,
  CreateManyDto,
} from '@nestjsx/crud';
import { ApiTags, ApiResponse, ApiOperation, ApiBody } from '@nestjs/swagger';
import { Appointment, AppointmentCreate } from './dtos/Appointment.dto';
import { AppointmentService } from './Appointment.service';

@Crud({
  model: {
    type: Appointment,
  },
  dto: {
    create: AppointmentCreate,
    update: Appointment,
    replace: Appointment,
  },
  query: {
    /**
     * commenting out limit and pagination because of an issue with Crud lib: https://github.com/nestjsx/crud/issues/777
     */
    // TODO: make limit env driven?
    limit: 5,
    alwaysPaginate: true,
  },
})
@Controller('Appointments')
@ApiTags('Appointments')
export class AppointmentController implements CrudController<Appointment> {
  constructor(public service: AppointmentService) {}

  get base(): CrudController<Appointment> {
    return this;
  }

  @Override('getManyBase')
  @ApiOperation({ summary: 'Retrieve multiple Appointments' })
  getMany(@ParsedRequest() req: CrudRequest) {
    return this.base.getManyBase(req);
  }

  @Override('getOneBase')
  @ApiOperation({ summary: 'Retrieve a single Appointment' })
  get(@ParsedRequest() req: CrudRequest) {
    return this.base.getOneBase(req);
  }

  @Override('createOneBase')
  @ApiOperation({ summary: 'Create a single Appointment' })
  @ApiBody({
    type: AppointmentCreate,
    description:
      'The Description for the Post Body. Please look into the DTO. You will see the @ApiOptionalProperty used to define the Schema.',
  })
  create(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Appointment) {
    return this.base.createOneBase(req, dto);
  }

  @Override('createManyBase')
  @ApiOperation({ summary: 'Create multipleAppointments' })
  createMany(
    @ParsedRequest() req: CrudRequest,
    @ParsedBody() dto: CreateManyDto<Appointment>,
  ) {
    return this.base.createManyBase(req, dto);
  }

  @Override('updateOneBase')
  @ApiOperation({ summary: 'Update a single Appointment' })
  update(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Appointment) {
    return this.base.updateOneBase(req, dto);
  }

  @Override('replaceOneBase')
  @ApiOperation({ summary: 'Replace a single Appointment' })
  replace(@ParsedRequest() req: CrudRequest, @ParsedBody() dto: Appointment) {
    return this.base.replaceOneBase(req, dto);
  }

  @Override('deleteOneBase')
  @ApiOperation({ summary: 'Delete a single Appointment' })
  delete(@ParsedRequest() req: CrudRequest) {
    return this.base.deleteOneBase(req);
  }
}
