/**
 * This file generated by Apso.
 */
import { PatientModule } from './Patient/Patient.module';
import { AppointmentModule } from './Appointment/Appointment.module';
import { ActivityModule } from './Activity/Activity.module';

export default [PatientModule, AppointmentModule, ActivityModule];
