/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Patient, PatientCreate } from './dtos/Patient.dto';
import { PatientController } from './Patient.controller';
import { PatientService } from './Patient.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('PatientController', () => {
  let controller: PatientController;
  let spyService: PatientService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: PatientService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [PatientController],
      providers: [PatientService, ApiServiceProvider],
    }).compile();

    controller = module.get<PatientController>(PatientController);
    spyService = module.get<PatientService>(PatientService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call PatientController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call PatientController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Patient();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
