/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Patient } from './Patient.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PatientService } from './Patient.service';
import { PatientController } from './Patient.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Patient])],
  providers: [PatientService],
  exports: [PatientService],
  controllers: [PatientController],
})
export class PatientModule {}
