import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PatientCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  dob: string;
  @ApiProperty()
  gender: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  email: string;
}

export class Patient {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  dob: string;
  @ApiProperty()
  gender: string;
  @ApiProperty()
  address: string;
  @ApiProperty()
  phone_number: string;
  @ApiProperty()
  email: string;
}
